2017-11-28 17:01:21,236 - INFO - __init__.py[line:8] - ansible version is 2.2.3.0
2017-11-28 17:01:33,942 - INFO - __init__.py[line:8] - ansible version is 2.2.3.0
2017-11-28 17:01:34,051 - INFO - _internal.py[line:87] -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2017-11-28 17:02:54,771 - INFO - display.py[line:153] - 	to retry, use: --limit @/etc/ansible/playbooks/k8s/install_flannel.retry

2017-11-28 17:02:54,853 - INFO - playbook.py[line:58] - [deploy] hosts: ['192.168.128.148','192.168.128.149'], playbook: /etc/ansible/playbooks/k8s/install_flannel.yml, extra_vars: {u'network_dir': u'/k8s/network', u'etcd_ip': u'192.168.128.139', 'hosts': "['192.168.128.148','192.168.128.149']", u'network_config': u'192.192.0.0/16', u'etcd_port': u'2379'}, result: {'failed': {}, 'success': {u'192.168.128.148': {u'config flannel': {'_ansible_parsed': True, u'group': u'root', u'uid': 0, '_ansible_no_log': False, u'changed': False, u'owner': u'root', u'state': u'file', u'gid': 0, u'mode': u'0644', u'path': u'/etc/sysconfig/flanneld', 'invocation': {u'module_args': {u'directory_mode': None, u'force': False, u'remote_src': None, u'path': u'/etc/sysconfig/flanneld', u'owner': None, u'follow': True, u'group': None, u'unsafe_writes': None, u'state': None, u'content': None, u'serole': None, u'diff_peek': None, u'setype': None, u'dest': u'/etc/sysconfig/flanneld', u'selevel': None, u'original_basename': u'flanneld.j2', u'regexp': None, u'validate': None, u'src': None, u'seuser': None, u'recurse': False, u'delimiter': None, u'mode': None, u'backup': None}}, u'diff': {u'after': {u'path': u'/etc/sysconfig/flanneld'}, u'before': {u'path': u'/etc/sysconfig/flanneld'}}, u'size': 388}, u'install flannel': {'_ansible_parsed': True, '_ansible_no_log': False, u'changed': False, u'results': [u'flannel-0.5.5-1.el7.x86_64 providing flannel is already installed'], u'msg': u'', u'rc': 0, 'invocation': {'module_name': u'yum', u'module_args': {u'name': [u'flannel'], u'list': None, u'disable_gpg_check': False, u'conf_file': None, u'install_repoquery': True, u'state': u'present', u'disablerepo': None, u'update_cache': False, u'enablerepo': None, u'exclude': None, u'validate_certs': True}}}}}, 'unreachable': {}}
2017-11-28 17:02:54,856 - INFO - _internal.py[line:87] - 127.0.0.1 - - [28/Nov/2017 17:02:54] "POST /deploy HTTP/1.1" 200 -
